GRANT CONNECT, CREATE TABLE, CREATE SYNONYM, CREATE VIEW, CREATE DATABASE LINK TO site1;
GRANT CONNECT, CREATE TABLE, CREATE SYNONYM, CREATE VIEW, CREATE DATABASE LINK TO site2;
GRANT CONNECT, CREATE TABLE, CREATE SYNONYM, CREATE VIEW, CREATE DATABASE LINK TO site3;
GRANT UNLIMITED TABLESPACE TO site1;
GRANT UNLIMITED TABLESPACE TO site2;
GRANT UNLIMITED TABLESPACE TO site3;
